import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Building2, CalendarCheck, Check, ClipboardCheck, Eye, MapPin, ShieldCheck, Sparkles } from "lucide-react";
import exteriorAsset from "@/assets/clean-scene-exterior-banner.jpeg.asset.json";
import interiorAsset from "@/assets/clean-scene-interior-banner.png.asset.json";
import { Button } from "@/components/ui/button";
import { QuoteForm } from "@/components/quote-form";
import { FinalCta } from "@/components/site-shell";

export const Route = createFileRoute("/")({
  head:()=>({meta:[{title:"Commercial Cleaning North Central Indiana | Clean Scene"},{name:"description",content:"Professional commercial and office cleaning for businesses in Lafayette, Delphi, Logansport, and North Central Indiana."},{property:"og:title",content:"Clean Scene Commercial Cleaning"},{property:"og:description",content:"Professional commercial cleaning built around your business space."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/"}]}),
  component: Index,
});

// IMPORTANT: Replace this placeholder. See ./README.md for routing conventions.
function Index() {
  const services=[
    ["Office Cleaning","Professional cleaning for offices, workspaces, conference rooms, break areas and shared spaces."],
    ["Lobbies & Common Areas","Keep entrances, reception areas, hallways and common spaces clean and presentable."],
    ["Commercial Facilities","Customized cleaning solutions for small and medium-sized business facilities."],
    ["Move-In / Move-Out Cleaning","Detailed cleaning to prepare commercial spaces for new occupants or their next use."],
    ["Daycare & Professional Spaces","Cleaning for facilities where attention to frequently touched surfaces is especially important."],
  ];
  return <>
    <section className="relative isolate min-h-[660px] overflow-hidden bg-primary"><img src={interiorAsset.url} alt="Clean Scene commercial cleaning banner featuring a modern lobby" className="absolute inset-0 h-full w-full object-cover object-center"/><div className="absolute inset-0 bg-hero-overlay"/><div className="relative mx-auto flex min-h-[660px] max-w-7xl items-end px-5 pb-16 pt-28 lg:px-8 lg:pb-20"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-hero-muted">Commercial cleaning · North Central Indiana</p><h1 className="mt-5 font-serif text-5xl leading-[1.08] text-hero sm:text-7xl">A Cleaner Space for Better Business.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-hero-muted">Professional commercial cleaning for offices, lobbies, common areas and business spaces throughout North Central Indiana.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-12 bg-background text-primary hover:bg-background/90"><Link to="/quote">Request a Free Quote <ArrowRight/></Link></Button><Button asChild size="lg" variant="outline" className="h-12 border-hero/60 bg-transparent text-hero hover:bg-hero/10 hover:text-hero"><Link to="/services">Explore Our Services</Link></Button></div></div></div></section>
    <section className="border-b border-border bg-background"><div className="mx-auto grid max-w-7xl divide-y divide-border md:grid-cols-3 md:divide-x md:divide-y-0">{[[ShieldCheck,"Professional","Commercial cleaning delivered with attention to presentation and detail."],[CalendarCheck,"Reliable","Consistent service built around the needs and schedule of your business."],[Eye,"Detail-Driven","Careful cleaning of the spaces employees, customers and visitors see every day."]].map(([Icon,title,copy])=><div key={String(title)} className="flex gap-4 px-6 py-9 lg:px-10"><Icon className="mt-1 size-6 shrink-0 text-accent-foreground"/><div><h2 className="text-sm font-bold uppercase tracking-widest text-primary">{String(title)}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{String(copy)}</p></div></div>)}</div></section>
    <section className="section"><div className="section-inner"><div className="max-w-2xl"><p className="eyebrow">Our Services</p><h2 className="section-title">Commercial Cleaning Built Around Your Space</h2><p className="section-copy">Every business is different. Clean Scene provides flexible commercial cleaning services designed around your facility, priorities and cleaning needs.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-lg border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{services.map(([title,copy],i)=><article key={title} className="bg-background p-7"><span className="font-serif text-3xl text-accent-foreground/60">0{i+1}</span><h3 className="mt-7 text-lg font-bold text-primary">{title}</h3><p className="mt-3 leading-7 text-muted-foreground">{copy}</p></article>)}</div><div className="mt-8 flex flex-col items-start justify-between gap-5 border-l-4 border-accent bg-secondary p-7 md:flex-row md:items-center"><div><h3 className="font-bold uppercase tracking-wider text-primary">Need something different?</h3><p className="mt-1 text-muted-foreground">Tell us about your facility and we’ll discuss what you need.</p></div><Button asChild><Link to="/quote">Request a Quote</Link></Button></div></div></section>
    <section className="bg-primary text-primary-foreground"><div className="mx-auto grid max-w-7xl lg:grid-cols-2"><img src={exteriorAsset.url} alt="Official Clean Scene banner with modern commercial office buildings" className="h-full min-h-[360px] w-full object-cover"/><div className="px-6 py-16 lg:px-16 lg:py-20"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary-foreground/65">Why Clean Scene</p><h2 className="mt-4 font-serif text-4xl">A Higher Standard for Your Business</h2><p className="mt-5 leading-8 text-primary-foreground/75">Clean Scene is focused on helping businesses maintain professional, welcoming spaces with service tailored to each property.</p><ul className="mt-8 grid gap-4 sm:grid-cols-2">{["Detail-focused service","Flexible cleaning plans","Professional communication","Commercial-focused service","Cleaning tailored to each property","Local North Central Indiana service"].map(x=><li key={x} className="flex gap-3 text-sm"><Check className="size-5 shrink-0 text-sage"/>{x}</li>)}</ul></div></div></section>
    <section className="section"><div className="section-inner"><div className="text-center"><p className="eyebrow">Simple from the start</p><h2 className="section-title">How It Works</h2></div><div className="mt-12 grid gap-8 md:grid-cols-3">{[[ClipboardCheck,"Tell Us About Your Space","Complete our quote form with information about your property and cleaning needs."],[Sparkles,"Receive Your Custom Quote","We review the details of your facility and cleaning requirements."],[Building2,"Get Your Space Clean","Once service is scheduled, Clean Scene takes care of the cleaning so you can focus on business."]].map(([Icon,title,copy],i)=><article key={String(title)} className="text-center"><div className="mx-auto grid size-14 place-items-center rounded-full bg-secondary text-primary"><Icon/></div><p className="mt-5 text-xs font-bold text-accent-foreground">STEP {i+1}</p><h3 className="mt-2 text-lg font-bold text-primary">{String(title)}</h3><p className="mt-3 leading-7 text-muted-foreground">{String(copy)}</p></article>)}</div></div></section>
    <section className="bg-muted"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><MapPin className="size-8 text-accent-foreground"/><h2 className="mt-5 font-serif text-4xl text-primary">Proudly Serving North Central Indiana</h2><p className="mt-5 leading-7 text-muted-foreground">Clean Scene serves businesses throughout North Central Indiana, including Lafayette, Delphi, Logansport and surrounding communities.</p><Button asChild variant="outline" className="mt-7"><Link to="/service-area">View Service Area</Link></Button></div><div className="rounded-lg bg-background p-7 lg:p-10"><h3 className="font-serif text-2xl text-primary">Not sure if you’re in our service area?</h3><p className="mt-3 text-muted-foreground">Send us your location and we’ll let you know.</p><div className="mt-7 flex flex-wrap gap-3">{["Lafayette","Delphi","Logansport","Surrounding communities"].map(x=><span key={x} className="rounded-full bg-secondary px-4 py-2 text-sm font-semibold text-primary">{x}</span>)}</div></div></div></section>
    <section className="section bg-background"><div className="section-inner"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">Request a Free Quote</p><h2 className="section-title">Let’s Talk About Your Space</h2><p className="section-copy">Share the essentials now. For detailed scheduling, service areas, and optional files, use our complete quote form.</p></div><div className="mt-10 rounded-lg border border-border bg-card p-5 shadow-soft sm:p-8"><QuoteForm compact/></div><div className="mt-5 text-center"><Link to="/quote" className="text-sm font-bold text-primary underline underline-offset-4">Open the complete quote form</Link></div></div></section>
    <FinalCta/>
  </>;
}
